### ISSUE TITLE
[Feature]: 用户申请成为讲师

### ISSUE THREAD

**Issue by lbzss** [cit965/kubecit-service#130]
### cit965 Web端版本

NA

### cit965 Server端版本

NA

### 功能描述以及必要性描述

NA

### 建议和方案

用户申请成为讲师，申请需管理员审核，审核完成后在讲师表中增加记录同时修改用户表中的用户角色，若用户已经是讲师角色则直接。新增申请记录表，字段如下：
| 字段               | 类型       | 描述                   |
|------------------|----------|----------------------|
| id               | int      | 申请记录id               |
| user_id          | int      | 用户id                 |
| detail           | varchar  | 讲师详情                 |
| curriculum_vitae | text     | 履历描述                 |
| works            | text     | 以往作品                 |
| skills           | varchar  | 技能点                  |
| name             | varchar  | 讲师名称                 |
| level            | int      | 级别                   |
| avatar           | varchar  | 头像                   |
| created_at       | datetime | 创建时间                 |
| updated_at       | datetime | 更新时间                 |
| is_passed        | int      | 是否通过（1通过，2不通过），默认为2  |
| messages         | text     | 审核意见                 |
| auditor_id       | text     | 审核人id                |
| archived         | int      | 是否归档(1已归档,2还未归档)默认为2 |

接口变更

| 方法    | 路径                        | 参数                                                                      | 描述                                                       |
|-------|---------------------------|-------------------------------------------------------------------------|----------------------------------------------------------|
| POST  | /api/teacher/become       | user_id,detail,curriculum_vitae,works,skills,name,level,avatar          | 申请成为讲师，先存在申请记录表中                                         |
| PATCH | /api/teacher/review/{id}  | auditor_id,messages,is_passed                                           | 审核记录，通过添加记录到teacher表中，同步修改user表对应记录role_id，归档记录，不通过也归档记录 |
| POST  | /api/teacher/becomeRecord | is_passed(optional),user_id(optional),id(optional),pagination(optional) | 查询用户的申请记录                                                |

用户申请不管通过还是驳回都修改archived状态为1，再次申请则增加新的记录。

**Comment by mouuii** [comment]
归档有必要吗？不懂是干嘛的
