### ISSUE TITLE
[Feature]: vip功能

### ISSUE THREAD

**Issue by lbzss** [cit965/kubecit-service#132]
### cit965 Web端版本

NA

### cit965 Server端版本

NA

### 功能描述以及必要性描述

用户vip信息相关接口

**Comment by lbzss** [comment]
目前设计是会员用户可以观看站内所有课程。成为会员接口
会员信息表结构

| 字段           | 类型       | 描述                            |
|--------------|----------|-------------------------------|
| id           | int      | 会员id                          |
| vip_type     | int      | 会员类型(月度会员1，季度会员2，年度会员3，永久会员4) |
| vip_type     | int      | 会员类型(月度会员1，季度会员2，年度会员3，永久会员4) |
| order_type   | int      | 支付类型（转账1，支付宝2，微信3，金叶子4，银叶子5）  |
| order_status | int      | 支付状态（1交易完成，2交易创建，3交易关闭）       |
| start_at     | datetime | 会员权益生效时间（默认值为当前时间）            |
| expire_at    | datetime | 会员权益失效时间                      |

会员商品表，用于修改价格等

| 字段        | 类型       | 描述                |
|-----------|----------|-------------------|
| id        | int      | 会员类型id            |
| price     | int      | 会员价格              |
| description     | text      | 会员描述              |

api修改及新增

| 方法   | 路径                         | 参数                                                                      | 描述                                        |
|------|----------------------------|-------------------------------------------------------------------------|-------------------------------------------|
| POST | /api/u/become              | vip_type                                                                | 成为vip，传入vip类型与支付方式，返回付款链接，用户支付后三方回调接口更新状态 |
| POST | /api/trade/callback/alipay | biz_no,trade_no                                                         | 三方支付平台回调接口，根据业务号和支付号等回传参数判断更新哪个支付记录       |
| Get  | /api/member/getInfo        |                                                          | 返回参数中增加vip是否激活                     |

**Comment by mouuii** [comment]
会员信息表怎么还有订单信息；vip_type写了两遍，多次充值会员怎么算？

**Comment by lbzss** [comment]
那就把会员的订单拆成单独的会员订单表吧，多次充值更新权益过期时间。

**Comment by lbzss** [comment]
会员信息表结构

| 字段        | 类型       | 描述                            |
|-----------|----------|-------------------------------|
| id        | int      | 会员id                          |
| vip_type  | int      | 会员类型(月度会员1，季度会员2，年度会员3，永久会员4) |
| order_id  | int      | 订单id                          |
| start_at  | datetime | 会员权益生效时间（默认值为当前时间）            |
| expire_at | datetime | 会员权益失效时间                      |
| user_id   | int      | 用户id                          |

会员订单表

| 字段           | 类型       | 描述                            |
|--------------|----------|-------------------------------|
| id           | int      | 会员订单id                        |
| biz_id       | varchar  | 业务订单号                         |
| vip_type     | int      | 会员类型(月度会员1，季度会员2，年度会员3，永久会员4) |
| order_type   | int      | 支付类型（转账1，支付宝2，微信3，金叶子4，银叶子5）  |
| order_status | int      | 支付状态（1交易完成，2交易创建，3交易关闭）       |
| create_at    | datetime | 创建时间                          |
| update_at    | datetime | 更新时间                          |
| user_id      | int      | 用户id                          |
| price        | float    | 订单价格                          |



会员商品表，用于后管修改价格等

| 字段        | 类型       | 描述                |
|-----------|----------|-------------------|
| id        | int      | 会员类型id            |
| price     | int      | 会员价格              |
| description     | text      | 会员描述              |

api修改及新增

| 方法   | 路径                         | 参数                                                                      | 描述                                         |
|------|----------------------------|-------------------------------------------------------------------------|--------------------------------------------|
| POST | /api/u/become              | vip_type                                                                | 成为vip，传入vip类型与支付方式，返回付款链接，用户支付后三方回调接口更新状态  |
| POST | /api/trade/callback/alipay | biz_no,trade_no                                                         | 三方支付平台回调接口，根据业务号和支付号等回传参数判断更新哪个支付记录(先mock) |
| Get  | /api/member/getInfo        |                                                          | 返回参数中增加vip是否激活                             |

**Comment by mouuii** [comment]
ok
