### ISSUE TITLE
[Feature]: 用户登录

### ISSUE THREAD

**Issue by mouuii** [cit965/kubecit-service#16]
### cit965 Web端版本

0

### cit965 Server端版本

0

### 功能描述以及必要性描述

1.用户登录需要加密客户端传过来的密码，具体加密算法咨询前端
2.目前只做账号密码登录

**Comment by LoveOyy** [comment]
assign me

**Comment by LoveOyy** [comment]
# 登录注册功能设计

## 数据库表设计

### accounts 账户表
| 字段名称     | 字段含义         | 字段类型        |
| ---------- |--------------| ---------- |
| id       | 账户id         | uint64      |
| user_id | users表中的用户id | uint64 |
| username | 用户名          | varchar(32) |
| password | MD5后密码       | varchar(32) |
| method | 登录方式         | varchar(32) |

### users 用户表
| 字段名称     | 字段含义 | 字段类型        |
| ---------- | ---------- | ---------- |
| id       | 用户id | uint64      |
| username | 用户名 | varchar(32) | 
| password | MD5后密码 | varchar(32) | 

```mermaid
classDiagram
class AccountRepository{
    <<interface 账号库>>
    +FindByUsernameAndMethod(ctx context.Context,username string,method string)(account *AccountPO,err error)
    +Save(ctx context.Context,account *AccountPO)err error
    
}

```

```mermaid
classDiagram
class UserRepository{
    <<interface 用户库>>
    +FindByID(ctx context.Context,id uint64)(user *UserPO,err error)
    +Save(ctx context.Context,user *UserPO)(err error)
    
}

```
```mermaid
classDiagram
class UserUseCase {
    <<interface 用户服务用例>>
    +Register(ctx context.Context,args *RegisterArgs) (reply *RegisterReply,err error)
    +Login(ctx context.Context,args *LoginArgs) (reply *LoginReply,err error)
}


```





```mermaid
sequenceDiagram


Client->>UserAuthMiddleware: request
alt success
UserAuthMiddleware->>NextMiddleware: gin.Context.Set("user_id",用户id)
end


Note left of Client: 客户端设置登录header kubecit-usertoken:token
Note left of UserAuthMiddleware: 登录认证中间件根据 header中 kubecit-usertoken 获取用户id 




```

**Comment by mouuii** [comment]
accounts 表是用来记录第三方登录的表吗？如果是的话，username 字段改为 openid 较好。

**Comment by LoveOyy** [comment]
accounts表记录 例如用户名登陆 微信登录 手机号登陆等信息

用户有多种登陆方式 accounts和users是多对1关系


### accounts 账户表
| 字段名称     | 字段含义         | 字段类型        |
| ---------- |--------------| ---------- |
| id       | 账户id         | uint64      |
| user_id | users表中的用户id | uint64 |
| openid | 用户名手机号或三方登陆身份标识          | varchar(32) |
| password | MD5后密码       | varchar(32) |
| method | 登录方式         | varchar(32) |

### users 用户表
| 字段名称     | 字段含义   | 字段类型       |
|----------|--------|------------|
| id       | 用户id   | uint64     |
| username | 用户名    | varchar(32) | 
| password | MD5后密码 | varchar(32) | 
| username | 用户名    | varchar(32) | 
| channel | 用户渠道 | varchar(64) |
| role_id  | 用户角色id | uint8      |
