### ISSUE TITLE
[Feature]: 首页轮播图

### ISSUE THREAD

**Issue by mouuii** [cit965/kubecit-service#18]
### cit965 Web端版本

0

### cit965 Server端版本

0

### 功能描述以及必要性描述

1.上传轮播图
2.展示轮播图
3更新轮播图
4.删除轮播图

### 建议和方案

轮播图需要有优先级

**Comment by lbzss** [comment]
### slider表结构设计
| 字段名称       | 字段类型         | 描述           |
|------------|--------------|--------------|
| id         | int          | 自增id         |
| title      | varchar(50)  | 轮播图标题        |
| content    | varchar(255) | 轮播图内容简介      |
| image_link | varchar(255) | 轮播图链接        |
| create_at  | timestamp    | 创建时间         |
| update_at  | timestamp    | 修改时间         |
| is_valid   | bool         | 是否有效，1有效，0无效 |
| priority   | int          | 优先级          |


### api设计
| 请求名称 | 方法     | api            | 参数 |
|------|--------|----------------|----|
| 创建轮播图   | post   | /api/slider    | *|
| 获取轮播图信息   | get    | /api/slider/id | |
| 删除轮播图   | delete | /api/slider/id | |
| 更新轮播图   | post   | /api/slider/id | *|
| 指定优先级获取轮播图列表   | post   | /api/sliders   |priority,count |
