### ISSUE TITLE
[Feature]: 查询个人信息

### ISSUE THREAD

**Issue by mouuii** [cit965/kubecit-service#21]
### cit965 Web端版本

0

### cit965 Server端版本

0

### 功能描述以及必要性描述

/api/member/getInfo

**Comment by kcxg** [comment]
从token 中解析出用户ID，然后去用户表中查看用户的信息

**Comment by kcxg** [comment]
@mouuii  是不是这样做

**Comment by mouuii** [comment]
/LGTM 可以和做注册登录的小伙伴交流下，前端传token，经过中间件解析出 用户id ，你只需要使用用户id查询用户详细信息
