### ISSUE TITLE
[Feature]: 购物车

### ISSUE THREAD

**Issue by mouuii** [cit965/kubecit-service#43]
### cit965 Web端版本

0

### cit965 Server端版本

0

### 功能描述以及必要性描述

能够记录用户购物车中东西

**Comment by kcxg** [comment]
| 字段名称	        | 类型       | 含义   |
| :----------- | :------- | :--- |
| id	          | int      | ID   |
| user\_id     | int      | 用户id |
| course\_id   | int      | 课程id |
| create\_time | datetime | 创建时间 |
| update\_time | datetime | 更新时间 |

**Comment by kcxg** [comment]
@mouuii   评审一下表结构

**Comment by mouuii** [comment]
购物车先不做了
