### ISSUE TITLE
[Feature]: 课程详情页面接口

### ISSUE THREAD

**Issue by mouuii** [cit965/kubecit-service#44]
### cit965 Web端版本

0

### cit965 Server端版本

0

### 功能描述以及必要性描述

https://xuexiluxian.cn/course/detail/024f978cc56e405d9ecb2ed1db442495 参考

**Comment by mouuii** [comment]
章节是不是也有个sort

**Comment by lbzss** [comment]
| 字段            | 类型     | 含义    |
|---------------|--------|-------|
| id            | int    | 章节ID  |
| name          | string | 章节名称  |
| released_time | time   | 发布时间  |
| description   | string | 章节描述  |
| sort          | int    | 排序位置    |
| course_id     | int    | 课程ID  |

**Comment by mouuii** [comment]
1.Lesson加上标识，标识是否是试看
2.Lesson加上来源，有可能视频来源于 b站，youtube

**Comment by lbzss** [comment]
引用其他视频源是否会有版权问题，还是说如果视频来自于其他源站则直接跳转至其他站点

**Comment by lbzss** [comment]
### Lesson
| 字段              | 类型     | 含义               |
|-----------------|--------|------------------|
| id              | int    | 课程ID             |
| name            | string | 课程名称             |
| released_time   | time   | 发布时间             |
| sort            | int    | 排序位置             |
| video           | string | 视频地址（oss?云盘?）    |
| courseware      | string | 课件地址             |
| chapter_id      | int    | 章节ID             |
| is_free_priview | int    | 是否试看(0否)（1是） |

### Chapter
| 字段            | 类型     | 含义    |
|---------------|--------|-------|
| id            | int    | 章节ID  |
| name          | string | 章节名称  |
| released_time | time   | 发布时间  |
| description   | string | 章节描述  |
| sort          | int    | 排序    |
| course_id     | int    | 课程ID  |
| hass_free_priview | int    | 是否有试看内容(0没有)（1有） |

**Comment by mouuii** [comment]
> 引用其他视频源是否会有版权问题，还是说如果视频来自于其他源站则直接跳转至其他站点

没有问题，跳转

**Comment by mouuii** [comment]
is_free_priview | int | 是否试看(0否)（1是）
-- | -- | --


 不要用 0 标识 ，1，2 标识

**Comment by lbzss** [comment]
### Lesson
| 字段              | 类型     | 含义               |
|-----------------|--------|------------------|
| id              | int    | 课程ID             |
| name            | string | 课程名称             |
| released_time   | time   | 发布时间             |
| sort            | int    | 排序位置             |
|type|int|课程类型(1 视频)（2 音频）|
| storage_path| string | 课程文件地址（oss?云盘?）    |
|source|string|课程源|
| courseware      | string | 课件地址             |
| chapter_id      | int    | 章节ID             |
| is_free_priview | int    | 是否试看(2否)（1是） |

### Chapter
| 字段            | 类型     | 含义    |
|---------------|--------|-------|
| id            | int    | 章节ID  |
| name          | string | 章节名称  |
| released_time | time   | 发布时间  |
| description   | string | 章节描述  |
| sort          | int    | 排序    |
| course_id     | int    | 课程ID  |
| hass_free_priview | int    | 是否有试看内容(2没有)（1有） |
