### ISSUE TITLE
[Feature]: 讲师详情页

### ISSUE THREAD

**Issue by mouuii** [cit965/kubecit-service#45]
### cit965 Web端版本

0

### cit965 Server端版本

0

### 功能描述以及必要性描述

展示讲师详情，履历描述，以往作品，技能点

**Comment by kcxg** [comment]
讲师表

| 字段名称              | 类型       | 含义   |
| :---------------- | :------- | :--- |
| teacher\_detail   | text     | 讲师详情 |
| curriculum\_vitae | text     | 履历描述 |
| works             | text     | 以往作品 |
| skill\_points     | text     | 技能点  |
| avator            | varchar  | 头像   |
| create\_time      | datetime | 创建时间 |
| update\_time      | datetime | 更新时间 |
