### ISSUE TITLE
[Feature]:  订单创建

### ISSUE THREAD

**Issue by kcxg** [cit965/kubecit-service#59]
### cit965 Web端版本

。

### cit965 Server端版本

。

### 功能描述以及必要性描述

订单创建

**Comment by kcxg** [comment]
订单商品表：

| 字段名称         | 类型       | 含义   |
| :----------- | :------- | :--- |
| id           | int      | ID   |
| order\_id     | int      |订单id |
| course\_id   | int      | 课程id |
| create\_time | datetime | 创建时间 |
| update\_time | datetime | 更新时间 |

订单表：

| 字段名称         | 类型       | 含义                               |
| :----------- | :------- | :------------------------------- |
| user\_id     | int      | 用户id                             |
| order\_sn    | varchar  | 订单号，我们平台自己生成的订单号                 |
| pay\_type    | int      | 支付类型    0 (支付宝)， 1 (微信)          |
| pay\_status  | int      | 支付状态  0(待支付), 1(成功)， 2(失败)，3（关闭） |
| trade\_no    | varchar  | 交易号   就是微信、支付宝的订单号 查账               |
| trade\_price    | float32  | 订单价格             |
| pay\_time    | datetime | 支付时间                             |
| create\_time | datetime | 创建时间                             |
| update\_time | datetime | 更新时间                             |

**Comment by Vingurzhou** [comment]
价格要不要用字符串，以防以后位数过多出现失精的情况

**Comment by mouuii** [comment]
> 价格要不要用字符串，以防以后位数过多出现失精的情况

可以用 decimal，或者int表示分

**Comment by kcxg** [comment]
> 订单状态加 ： 退款中，退款成功，订单取消 订单商品表叫做订单明细，应该再加一个商品名称，商品价格，商品描述

这个我们的商品不就是课程吗，这些信息通过课程id 不就可以关联出来吗

**Comment by mouuii** [comment]
> > 订单状态加 ： 退款中，退款成功，订单取消 订单商品表叫做订单明细，应该再加一个商品名称，商品价格，商品描述
> 
> 这个我们的商品不就是课程吗，这些信息通过课程id 不就可以关联出来吗

订单商品明细表记录的是某一时刻的商品信息，理论上最好有个非关系型记录当时商品的一切信息，用id关联没用的，会变化

**Comment by kcxg** [comment]
订单明细表：

| 字段名称             | 类型       | 含义   |
| :--------------- | :------- | :--- |
| id               | int      | ID   |
| order\_id        | int      | 订单id |
| course\_id       | int      | 课程id |
| course\_name     | varchar  | 名称	  |
| course\_price    | varchar  | 价格   |
| course\_describe | varchar  | 描述   |
| create\_time     | datetime | 创建时间 |
| update\_time     | datetime | 更新时间 |

订单表：

| 字段名称         | 类型       | 含义                                                    |
| :----------- | :------- | :---------------------------------------------------- |
| user\_id     | int      | 用户id                                                  |
| order\_sn    | varchar  | 订单号，我们平台自己生成的订单号                                      |
| pay\_type    | int      | 支付类型    0 (支付宝)， 1 (微信)                               |
| pay\_status  | int      | 支付状态  0(待支付), 1(成功)， 2(失败)，3（关闭）4(订单取消) 5(退款中)6（退款取消） |
| trade\_price | varchar  | 订单价格                                                  |
| trade\_no    | varchar  | 交易号   就是微信、支付宝的订单号 查账                                 |
| pay\_time    | datetime | 支付时间                                                  |
| create\_time | datetime | 创建时间                                                  |
| update\_time | datetime | 更新时间                                                  |

**Comment by kcxg** [comment]
订单明细表：

| 字段名称             | 类型       | 含义   |
| :--------------- | :------- | :--- |
| id               | int      | ID   |
| order\_id        | int      | 订单id |
| course\_id       | int      | 课程id |
| course\_name     | varchar  | 名称	  |
| course\_price    | decimal  | 价格   |
| course\_describe | varchar  | 描述   |
| create\_time     | datetime | 创建时间 |
| update\_time     | datetime | 更新时间 |

订单表：

| 字段名称         | 类型       | 含义                                                    |
| :----------- | :------- | :---------------------------------------------------- |
| user\_id     | int      | 用户id                                                  |
| order\_sn    | varchar  | 订单号，我们平台自己生成的订单号                                      |
| pay\_type    | int      | 支付类型    0 (支付宝)， 1 (微信)                               |
| pay\_status  | int      | 支付状态  0(待支付), 1(成功)， 2(失败)，3（关闭）4(订单取消) 5(退款中)6（退款取消） |
| trade\_price | decimal  | 订单价格                                                  |
| trade\_no    | varchar  | 交易号   就是微信、支付宝的订单号 查账                                 |
| pay\_time    | datetime | 支付时间                                                  |
| create\_time | datetime | 创建时间                                                  |
| update\_time | datetime | 更新时间                                                  |
